
DROP TABLE IF EXISTS BAJAJ_DM.F_daily;
CREATE TABLE BAJAJ_DM.F_daily (
  AGREEMENTNO varchar(20) DEFAULT NULL,
  PARENT_AGREEMENTNO varchar(20) DEFAULT NULL
) ENGINE=MDB DEFAULT CHARSET=utf8 PARTITION BY KEY(AGREEMENTNO);

INSERT INTO BAJAJ_DM.F_daily (AGREEMENTNO, PARENT_AGREEMENTNO) (
    SELECT AGREEMENTNO, PARENT_AGREEMENTNO FROM bajaj_orig.factdaily
);

