----------------------
-- RANK Customer AMTFIN
-- 10 loans for particular CUSTOMERID
-- AMTFIN amount taken,
-- rows: 16M, speed:
SELECT DC.CUSTOMERID,FM.PRODUCTFLAG,FM.AMTFIN,RANK() OVER ( PARTITION BY DC.CUSTOMERID ORDER BY FM.AMTFIN DESC )
FROM facmonthly FM
JOIN DimCustomer DC ON FM.CUSTOMERKEY=DC.CUSTOMERKEY
WHERE FM.BUSINESS_DATE='2015-05-31'

SELECT DC.CUSTOMERID,FM.PRODUCTFLAG,FM.AMTFIN
FROM BAJAJ_DM.F_monthly2 FM
JOIN BAJAJ_DM.F_customer DC ON FM.CUSTOMERKEY=DC.CUSTOMERKEY
WHERE FM.BUSINESS_DATE='2015-05-31'
ORDER BY FM.AMTFIN DESC;
