SELECT DC.CUSTOMERID,FM.d_productflag_id,FM.AMTFIN
FROM BAJAJ_DM.F_monthly2 FM
JOIN BAJAJ_DM.F_customer DC ON FM.CUSTOMERKEY=DC.CUSTOMERKEY
JOIN BAJAJ_DM.F_cust_scd DS ON DC.CUSTOMERID=DS.CUSTOMERID AND DS.MAILINGADDRESS='Y'
WHERE FM.BUSINESS_DATE='2015-05-31' 
ORDER BY FM.AMTFIN DESC;
-- 2626083 rows in set (41.53 sec)

