SELECT FM.AGREEMENTNO ,FM.PARENT_LAN_PRODUCT , FDP.PRODUCTFLAG
FROM BAJAJ_DM.F_monthly1 FM
INNER JOIN BAJAJ_DM.F_daily FDC ON FM.AGREEMENTNO  = FDC.AGREEMENTNO
INNER JOIN BAJAJ_DM.F_daily FDP ON FDP.AGREEMENTNO = FDC.PARENT_AGREEMENTNO
WHERE FM.BUSINESS_DATE='2015-05-31'
AND IFNULL(FM.PARENT_LAN_PRODUCT, '') <> IFNULL(FDP.PRODUCTFLAG, '');




------ PARENT_PRODUCT_RECON BETWEEN FM and FD
-- FactDaily - daily snapshot daily refresh. Reconsciliation between PARENT_LAN_PRODUCT and PRODUCTFLAG
select FM.AGREEMENTNO ,FM.PARENT_LAN_PRODUCT , FDP.PRODUCTFLAG
from DM_BAFL..facmonthly FM
INNER JOIN DM_BAFL..FactDaily FDC ON FM.AGREEMENTNO  = FDC.AGREEMENTNO
INNER JOIN DM_BAFL..FactDaily FDP ON FDP.AGREEMENTNO  = FDC.PARENT_AGREEMENTNO
WHERE FM.BUSINESS_DATE='31-Jul-15'
AND ISNULL(FM.PARENT_LAN_PRODUCT ,'')<> ISNULL(FDP.PRODUCTFLAG ,'');
