-- Using F_monthly1
SELECT FM.AGREEMENTNO ,FM.PARENT_LAN_PRODUCT , FDP.PRODUCTFLAG
FROM BAJAJ_DM.F_monthly1 FM
JOIN BAJAJ_DM.F_daily FDC ON FM.AGREEMENTNO  = FDC.AGREEMENTNO
JOIN BAJAJ_DM.F_daily FDP ON FDP.AGREEMENTNO = FDC.PARENT_AGREEMENTNO
WHERE FM.BUSINESS_DATE='2015-05-31'
AND IFNULL(FM.PARENT_LAN_PRODUCT, '') <> IFNULL(FDP.PRODUCTFLAG, '');


-- Using F_monthly2
SELECT FM.AGREEMENTNO ,FMPL.name, FDP.d_productflag_id
FROM BAJAJ_DM.F_monthly2 FM
JOIN BAJAJ_DM.F_daily FDC ON FM.AGREEMENTNO  = FDC.AGREEMENTNO
JOIN BAJAJ_DM.F_daily FDP ON FDP.AGREEMENTNO = FDC.PARENT_AGREEMENTNO
JOIN BAJAJ_DM.D_parent_lan_product FMPL ON FMPL.id = FM.d_parent_lan_product_id
JOIN BAJAJ_DM.D_productflag_daily FDPF ON FDPF.id = FDP.d_productflag_id
WHERE FM.BUSINESS_DATE='2015-05-31'
AND FMPL.name <> FDPF.name LIMIT 100;




------ PARENT_PRODUCT_RECON BETWEEN FM and FD
-- FactDaily - daily snapshot daily refresh. Reconsciliation between PARENT_LAN_PRODUCT and PRODUCTFLAG
select FM.AGREEMENTNO ,FM.PARENT_LAN_PRODUCT , FDP.PRODUCTFLAG
from DM_BAFL..facmonthly FM
INNER JOIN DM_BAFL..FactDaily FDC ON FM.AGREEMENTNO  = FDC.AGREEMENTNO
INNER JOIN DM_BAFL..FactDaily FDP ON FDP.AGREEMENTNO  = FDC.PARENT_AGREEMENTNO
WHERE FM.BUSINESS_DATE='31-Jul-15'
AND ISNULL(FM.PARENT_LAN_PRODUCT ,'')<> ISNULL(FDP.PRODUCTFLAG ,'');
